name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up NPM & Yarn
        uses: volta-cli/action@v1

      - name: 'Get yarn cache directory path'
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 'Restore yarn cache if available'
        uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 'Check lint issues'
        run: |
          yarn install --frozen-lockfile --production=false
          yarn lint

  tests:
    runs-on: ubuntu-latest
    needs: lint-check
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up NPM & Yarn
        uses: volta-cli/action@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache if available
        uses: actions/cache@v2.1.6
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run tests
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile --production=false
          yarn test
